# NumPy

1. NumPy is a Python library.
2. Provides multidimensional array object, various derived objects, fast operations on array.


# Why is NumPy fast?

NumPy is fast because it uses optimized C code, processes data in contiguous memory blocks, and leverages vectorized operations to minimize Python overhead.

# NumPy quickstart

In [1]:
# In Numpy dimensions are called axes.
import numpy as np

In [3]:
# Display 0 to 14 , excluding 15
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# Size of array in dimensions (rows,column)
a.shape

(3, 5)

In [11]:
# Dimensions
a.ndim

2

In [8]:
a.dtype

dtype('int32')

In [12]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [13]:
a.size  #no of elements

15

In [14]:
type(a)

numpy.ndarray

In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
b = np.array([6,7,8])

In [17]:
b

array([6, 7, 8])

In [18]:
print(b)

[6 7 8]


In [19]:
print(type(b))

<class 'numpy.ndarray'>


# Array Creation

In [24]:
# Using array() function
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [21]:
a.dtype

dtype('int32')

In [22]:
b = np.array([1.2,3.2,5.6])
b

array([1.2, 3.2, 5.6])

In [23]:
b.dtype

dtype('float64')

In [29]:
# np.array(0 function 1 to 2 arguments)
# first argument as data, and optional second argument as dtype(that provides additional information)
'''
a = np.array(1,2,3,4)  # wrong
'''
# we are providing 4 separate positional arguments which is not allowed

'\na = np.array(1,2,3,4)  # wrong\n'

In [39]:
a = np.array((12,3,4,5,6))  # first argument as tuple
a

# note ans will contain []

array([12,  3,  4,  5,  6])

In [32]:
c = np.array(np.arange(4))  # NumPy array
c

array([0, 1, 2, 3])

In [34]:
a = np.array([(1.5,2,3),(4,5,6)])
a

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
a = np.array([(15,2,3),(4,5,6)])
a

array([[15,  2,  3],
       [ 4,  5,  6]])

In [42]:
# The type of the array can be explicitly specified at creation time:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [43]:
c = np.array([[1,2],[3,4]], dtype=float)
c

array([[1., 2.],
       [3., 4.]])

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

#### zeros()

In [49]:
'Creates an array full of zeros'
a = np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
# Defining the dtype
a = np.zeros((3,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
a = np.zeros((3,4), dtype=complex)
a

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

#### ones()

In [52]:
'Creates an array full of ones'
a = np.ones((1,2))
a

array([[1., 1.]])

In [64]:
a = np.ones((2,2), dtype=int)
a

# if dtype=None then it will return by default dtype = float

array([[1, 1],
       [1, 1]])

#### empty()

In [54]:
'Creates an array whose initial content is random and depends on the state of memory'
a = np.empty((2,2))
a

array([[1., 2.],
       [3., 4.]])

In [55]:
a = np.empty((2,3))
a

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#### arange()

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [58]:
# Basic usage:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [65]:
# Specifying Start and Stop:
b = np.arange(10,30)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [66]:
# Specifying the step size:
b = np.arange(10,30,5)
b

array([10, 15, 20, 25])

In [67]:
# Using floating Point steps:
c = np.arange(0,2,0.3)
c

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [68]:
# Specifying Data Type
arr = np.arange(1,5, dtype=float)
arr

array([1., 2., 3., 4.])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

#### linspace()

In [2]:
import numpy as np
from numpy import pi
a = np.linspace(0,2,9)   # 9 numbers from 0 to 9
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [3]:
b = np.linspace(0,10,4) # 4 numbers from 0 to 10      
b

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [4]:
# Using linspace:
import numpy as np
# Generate 5 values from 0 to 10
arr = np.linspace(0,10,num=5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [5]:
# Using arange:
import numpy as np
# Generate values from 0 to 10 with step 2
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [6]:
# Precision issue with arange:
import numpy as np
# Floating point issue with arange
arr = np.arange(0,1,0.1)
arr

# Depending on the precision this may or may not include 1.0

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [7]:
# Predictable Results with linspace:

import numpy as np
# floating point safe
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
print(a)

[0 1 2 3 4 5]


One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [11]:
# 1-D array:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
# 2-D array:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# 3-D array:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
c = np.arange(24).reshape(3,2,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [22]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [23]:
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])